import { HISTORY } from "./plugin-types";

export const defaultPlugins = [
  HISTORY,
  'paintFormat',
  'removeFormat',
  'line',
  'headings',
  'fontSize',
  'lineHeight',
  'letterSpacing',
  'line',
  'color',
  'bold',
  'italic',
  'underline',
  'strikethrough',
  'line',
  'superscript',
  'subscript',
  'inlineCode',
  'line',
  'indent',
  'align',
  'line',
  'unorderedList',
  'orderedList',
  'block-quote',
  'block-code',
  'line',
  'linkEditor',
  'hr',
  'clear-all',
  'line',
  'fullscreen'
];
