import { HISTORY } from "./plugin-types";

export const defaultPlugins = [
  HISTORY,
  'line',
  'fontSize',
  'lineHeight',
  'letterSpacing',
  'line',
  'textColor',
  'bold',
  'italic',
  'underline',
  'strikethrough',
  'line',
  'superscript',
  'subscript',
  'format-clear',
  'line',
  'indent',
  'align',
  'line',
  'headings',
  'bulleted-list',
  'numbered-list',
  'block-quote',
  'block-code',
  'line',
  'linkEditor',
  'hr',
  'clear-all',
  'line',
  'fullscreen'
];
